export default {
  SCHEMA_NOT_FOUND: 1,
  INVALID_HEADER: 2,
  INVALID_INPUT_DATA: 3,
  INVALID_INPUT_DATA_TYPE: 4,
  INVALID_INPUT_DATA_VALUE: 5,
  INVALID_BINARY_DATA: 6,
  EMPTY_REQUIRED_FIELD: 7,
  PACK_ERROR: 8,
  UNPACK_ERROR: 9,
  INCORRECT_PACKET_SIZE: 10,
  INVALID_RPC_INPUT_DATA: 11,
}